# theme: jekyll-theme-minimal
remote_theme: nkymut/just-the-docs
# https://github.com/mmistakes/minimal-mistakes
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"

show_downloads: "true"
google_analytics: G-GX0HTR3LCT
ga_tracking: G-GX0HTR3LCT

layout: page
title: ""


# Aux links for the upper right navigation
aux_links:
  "microbit-webueb-p5js on GitHub":
    - "//github.com/nkymut/microbit-webusb-p5js"
  "microbit-webble-p5js on GitHub":
    - "//github.com/nkymut/microbit-webble-p5js"


# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false