# theme: jekyll-theme-minimal
remote_theme: nkymut/just-the-docs
# https://github.com/mmistakes/minimal-mistakes
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"

show_downloads: "true"
google_analytics: G-GX0HTR3LCT
ga_tracking: G-GX0HTR3LCT

layout: page
title: ""
summary: この記事は、p5.jsからWebUSBやWebBluetooth経由でmicro:bitのボタンやセンサ入力のやり取りする方法を紹介します。
# logo: https://nkymut.github.io/p5-advent-2022/assets/p5js_microbit_logo.png
image: https://nkymut.github.io/p5-advent-2022/assets/WebBle_lightsensor2.png
largeimage: https://nkymut.github.io/p5-advent-2022/assets/WebBle_lightsensor2.png
date: 09/12/2022

# Aux links for the upper right navigation
aux_links:
  "microbit-webueb-p5js on GitHub":
    - "//github.com/nkymut/microbit-webusb-p5js"
  "microbit-webble-p5js on GitHub":
    - "//github.com/nkymut/microbit-webble-p5js"


# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false


twitter:
  username: nkymuta
  card: summary_large_image
  image: https://nkymut.github.io/p5-advent-2022/assets/p5js_microbit_logo.png
  summary_largeimage: https://nkymut.github.io/p5-advent-2022/assets/WebBle_lightsensor2.png
  summary: この記事は、p5.jsからWebUSBやWebBluetooth経由でmicro:bitのボタンやセンサ入力のやり取りする方法を紹介します。
